version: "2"
linters:
  enable:
    - misspell
    - revive
    - sloglint
  disable:
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
    revive:
      rules:
        - name: unused-parameter
          severity: warning
          disabled: true
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - govet
        path: _test.go
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/prometheus/snmp_exporter)
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/prometheus/snmp_exporter
