---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.17.1

executors:
  # Whenever the Go version is updated here, .promu.yml
  # should also be updated.
  golang:
    docker:
    - image: cimg/go:1.26
    parameters:
      working_dir:
        type: string
        default: ~/project
    working_directory: << parameters.working_dir >>

jobs:
  mixin:
    executor: golang

    steps:
    - checkout
    - run: go install github.com/monitoring-mixins/mixtool/cmd/mixtool@latest
    - run: go install github.com/google/go-jsonnet/cmd/jsonnetfmt@latest
    - run: make -C snmp-mixin lint build

workflows:
  version: 2
  snmp_exporter:
    jobs:
    - mixin:
        filters:
          tags:
            only: /.*/
