{
 "title": "SNMP / Ubiquiti Access Point",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "devices",
    "label": "Devices",
    "query": {
     "query": "label_values(up{job=~\"snmp.*\"}, instance)"
    }
   },
   {
    "name": "device_interfaces",
    "label": "Interface",
    "query": {
     "query": "query_result(ifOperStatus{job=~\"snmp.*\",instance=\"$devices\"}==1)"
    }
   },
   {
    "name": "device_model",
    "query": {
     "query": "label_values(unifiApSystemModel{job=~\"snmp.*\",instance=\"$devices\"}, unifiApSystemModel)"
    }
   },
   {
    "name": "device_firmware_version",
    "query": {
     "query": "label_values(unifiApSystemVersion{job=~\"snmp.*\",instance=\"$devices\"}, unifiApSystemVersion)"
    }
   },
   {
    "name": "device_mac_addresses",
    "query": {
     "query": "label_values(ifPhysAddress{job=~\"snmp.*\",instance=\"$devices\"}, ifPhysAddress)"
    }
   },
   {
    "name": "device_main_ip",
    "query": {
     "query": "label_values(unifiApSystemIp{job=~\"snmp.*\",instance=\"$devices\"}, unifiApSystemIp)"
    }
   },
   {
    "name": "device_ESSIDs",
    "label": "Interface",
    "query": {
     "query": "label_values(unifiVapEssId{job=~\"snmp.*\",instance=\"$devices\"}, unifiVapEssId)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic on the air",
   "type": "graph",
   "description": "How much traffic is on the air and going through this particular access point?",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxBytes{job=~\"snmp.*\",instance=\"$devices\"}[5m]))*8",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(unifiVapTxBytes{job=~\"snmp.*\",instance=\"$devices\"}[5m]))*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Packets on the air",
   "type": "graph",
   "description": "How many packets are on the air and going through this particular access point?\n\nIf this graph spikes up relative to the traffic numbers, you might see degraded overall throughput.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxPackets{job=~\"snmp.*\",instance=\"$devices\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(unifiVapRxDropped{job=~\"snmp.*\",instance=\"$devices\"}[5m]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(irate(unifiVapRxErrors{job=~\"snmp.*\",instance=\"$devices\"}[5m]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(irate(unifiVapTxPackets{job=~\"snmp.*\",instance=\"$devices\"}[5m]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(irate(unifiVapTxDropped{job=~\"snmp.*\",instance=\"$devices\"}[5m]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(irate(unifiVapTxErrors{job=~\"snmp.*\",instance=\"$devices\"}[5m]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  {
   "title": "Traffic on the wire",
   "type": "graph",
   "description": "How much traffic is coming from and going to this particular access point into the wired network?\n\nIf this empty, the access point is likely in wireless relay mode.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifHCInOctets{instance=\"$devices\",ifName=~\"eth.*\"}[5m]))*8",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(ifHCOutOctets{instance=\"$devices\",ifName=~\"eth.*\"}[5m]))*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Packets on the wire",
   "type": "graph",
   "description": "How many packets are coming from and going to this particular access point into the wired network?\n\nIf this empty, the access point is likely in wireless relay mode.\n\nIf this graph spikes up relative to the traffic numbers, you might see degraded overall throughput.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(unifiIfRxPackets{job=~\"snmp.*\",instance=\"$devices\"}[5m])",
     "legendFormat": "In"
    },
    {
     "expr": "irate(unifiIfRxMulticast{job=~\"snmp.*\",instance=\"$devices\"}[5m])",
     "legendFormat": "In, multicast"
    },
    {
     "expr": "irate(unifiIfRxDropped{job=~\"snmp.*\",instance=\"$devices\"}[5m])",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "irate(unifiIfRxError{job=~\"snmp.*\",instance=\"$devices\"}[5m])",
     "legendFormat": "In, error"
    },
    {
     "expr": "irate(unifiIfTxPackets{job=~\"snmp.*\",instance=\"$devices\"}[5m])",
     "legendFormat": "Out"
    },
    {
     "expr": "irate(unifiIfTxMulticast{job=~\"snmp.*\",instance=\"$devices\"}[5m])",
     "legendFormat": "Out, multicast"
    },
    {
     "expr": "irate(unifiIfTxDropped{job=~\"snmp.*\",instance=\"$devices\"}[5m])",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "irate(unifiIfTxError{job=~\"snmp.*\",instance=\"$devices\"}[5m])",
     "legendFormat": "Out, error"
    }
   ]
  },
  { "title": "Health & info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Load average",
   "type": "graph",
   "description": "This is the Linux load average as per https://en.wikipedia.org/wiki/Load_(computing)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "laLoadFloat{instance=\"$devices\",laIndex=\"1\"}",
     "legendFormat": "1 minute"
    },
    {
     "expr": "laLoadFloat{instance=\"$devices\",laIndex=\"2\"}",
     "legendFormat": "5 minutes"
    },
    {
     "expr": "laLoadFloat{instance=\"$devices\",laIndex=\"3\"}",
     "legendFormat": "15 minutes"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "memTotalReal{instance=\"$devices\"} - memTotalFree{instance=\"$devices\"}",
     "legendFormat": "Used, absolute"
    },
    {
     "expr": "(memTotalReal{instance=\"$devices\"} - memTotalFree{instance=\"$devices\"}) / memTotalReal{instance=\"$devices\"}",
     "legendFormat": "Used, relative"
    }
   ]
  },
  {
   "title": "$devices information",
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 40 },
   "options": {
    "content": "Model: $device_model  \nFirmware: $device_firmware_version  \nMain IP: $device_main_ip\n\n"
   },
   "targets": [
    { "expr": "{{$device_model}}" }
   ]
  },
  {
   "title": "$devices ESSIDs",
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 40 },
   "options": { "content": "${device_ESSIDs}" },
   "targets": [
    { "expr": "{{$device_model}}" }
   ]
  },
  {
   "title": "$devices MAC",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
   "options": { "content": "$device_mac_addresses" },
   "targets": [
    { "expr": "{{$device_model}}" }
   ]
  },
  {
   "title": "Job response times",
   "type": "graph",
   "description": "This is split into the internal parts of snmp_exporter to show where any timing problems come from.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=~\"snmp.*\",instance=\"$devices\"}",
     "legendFormat": "Total job, Prometheus point of view"
    },
    {
     "expr": "snmp_scrape_duration_seconds{job=~\"snmp.*\",instance=\"$devices\"}",
     "legendFormat": "snmp_exporter, internal"
    },
    {
     "expr": "snmp_scrape_walk_duration_seconds{job=~\"snmp.*\",instance=\"$devices\"}",
     "legendFormat": "snmp_exporter, just SNMP"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "repeat": "device_interfaces",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifHCInOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(ifHCOutOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifHCInOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(ifHCOutOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifHCInOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(ifHCOutOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifHCInOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(ifHCOutOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifHCInOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(ifHCOutOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifHCInOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(ifHCOutOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifHCInOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(ifHCOutOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifHCInOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(ifHCOutOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifHCInOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(ifHCOutOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifHCInOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(ifHCOutOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Bits - $device_interfaces ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifHCInOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(ifHCOutOctets{instance=\"$devices\",ifName=\"$device_interfaces\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  }
 ]
}