---
name: Generator
on:
  pull_request:
  push:
    branches: [main, 'release-*']
    tags: ['v*']

permissions:
  contents: read

jobs:
  generator:
    name: Build generator
    runs-on: ubuntu-latest
    container:
      # Whenever the Go version is updated here, .promu.yml
      # should also be updated.
      image: quay.io/prometheus/golang-builder:1.26-base
    defaults:
      run:
        working-directory: ./generator
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: prometheus/promci-setup@55bd31fe92710532260eb57c554f2697363285c5 # v0.2.2
      - run: apt-get update
      - run: apt-get -y install build-essential diffutils libsnmp-dev p7zip-full
      - run: make mibs
      - run: make generator
      - run: make parse_errors
      - run: make generate
      - run: git diff --exit-code
      - uses: prometheus/promci-artifacts/save@9ca3252d07f230d5f923452b4df5697eba4a5bee # v0.1.1
        with:
          directory: generator

  publish_generator_main:
    name: Publish generator main branch artifacts
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [generator]
    if: |
      (github.event_name == 'push' && github.event.ref == 'refs/heads/main')
    steps:
      - uses: prometheus/promci/publish_main@872d318d090d73df349cb6ed90aadd072ca478f7 # v0.10.0
        with:
          docker_hub_login: ${{ secrets.docker_hub_login }}
          docker_hub_password: ${{ secrets.docker_hub_password }}
          ghcr_io_password: ${{ github.token }}
          quay_io_login: ${{ secrets.quay_io_login }}
          quay_io_password: ${{ secrets.quay_io_password }}
          working_directory: generator
          skip_manifest: true

  publish_generator_release:
    name: Publish generator release artefacts
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [generator]
    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
    steps:
      - uses: prometheus/promci/publish_release@872d318d090d73df349cb6ed90aadd072ca478f7 # v0.10.0
        with:
          docker_hub_login: ${{ secrets.docker_hub_login }}
          docker_hub_password: ${{ secrets.docker_hub_password }}
          ghcr_io_password: ${{ github.token }}
          quay_io_login: ${{ secrets.quay_io_login }}
          quay_io_password: ${{ secrets.quay_io_password }}
          working_directory: generator
          skip_manifest: true
          skip_github_release: true
